// generated by build.py from fonts.toml, do not edit
const FONTS = {
  "Sans-serif": [
    "Apfel Grotezk",
    "Aspekta",
    "AUTHENTIC Sans",
    "BDO Grotesk",
    "Breite Grotesk",
    "DM Sans",
    "Geist",
    "General Sans",
    "Haskoy",
    "Helvetica",
    "Helvetica Neue",
    "Host Grotesk",
    "IBM Plex Sans",
    "Inclusive Sans",
    "Instrument Sans",
    "Inter",
    "Kecal",
    "Manrope",
    "Montserrat",
    "Open Sauce Sans",
    "Opening Hours Sans",
    "Outfit",
    "Plus Jakarta Sans",
    "Pretendard",
    "Public Sans",
    "Red Hat Text",
    "Rethink Sans",
    "Satoshi",
    "Space Grotesk",
    "Uncut Sans",
    "Urbanist",
    "Violet Sans",
    "Work Sans",
    "sans-serif",
    "system-ui"
  ],
  "Serif": [
    "Times New Roman",
    "serif"
  ],
  "Monospace": [
    "Cascadia Code",
    "DM Mono",
    "Geist Mono",
    "Google Sans Code",
    "IBM Plex Mono",
    "Inconsolata",
    "Ioskeley Mono",
    "JetBrains Mono",
    "Monaspace Neon Var",
    "Red Hat Mono",
    "Reddit Mono",
    "Space Mono",
    "Victor Mono",
    "monospace"
  ],
  "Display": [
    "Geist Pixel",
    "PP Mondwest",
    "PP NeueBit",
    "Terminal Grotesque",
    "Terminal Grotesque Open"
  ]
};
const INSTALLED_ONLY = ["PP Mondwest", "PP NeueBit", "Helvetica", "Helvetica Neue", "Times New Roman"];
